### ISSUE TITLE
Config checkout fails when project is checked out with custom ref

### ISSUE THREAD

**Issue by nicorikken** [oss-review-toolkit/ort-ci-github-action#16]
It seems that somehow the git refs are mixed up. If I check out the project with a custom ref, the action will try to checkout the config with that ref as well:

```bash
Run oss-review-toolkit/ort-ci-github-action@main
Run echo -e "\e[1;33m Initializing ORT in GitHub workspace... "
 Initializing ORT in GitHub workspace... 
Run if [[ -z "$(ls -A ${ORT_CONFIG_PATH})" ]]; then
 Retrieving ORT config ORT from https://github.com/oss-review-toolkit/ort-config.git... 
fatal: couldn't find remote ref main-2.0
Error: Process completed with exit code 128.
```

Workflow file excerpt:
```yaml
# ...
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        repository: alliander-opensource/weather-provider-api
        ref: main-2.0 # <-- SOMEHOW THIS REF IS USED
        token: ${{secrets.XXX }}

    - name: Clone ORT config
      uses: actions/checkout@v2
      with:
        repository: alliander/ospo-ort-config
        path: ~/.ort/ort-config
        token: ${{secrets.XXX }}

    - name: OSPO License scanning
      uses: oss-review-toolkit/ort-ci-github-action@main
      with:
        run: 'analyzer,reporter,upload-results'
        sw-name: weather_provider_api
```

With variables:
```
    ORT_CONFIG_PATH: /home/runner/.ort/config
    ORT_CONFIG_VCS_URL: https://github.com/oss-review-toolkit/ort-config.git
    ORT_CONFIG_VCS_REVISION: 
```

Apparently it remembers the git ref as it is already in a git repo?

**Comment by tsteenbe** [comment]
Maybe not setting a default value for ORT_CONFIG_VCS_REVISION is causing ref 'main-2.0' to be used. I know set a default value - can you try it again?

**Comment by nicorikken** [comment]
Fixed! Thanks @tsteenbe

**Comment by tsteenbe** [comment]
@nicorikken  For me using `actions/checkout` with `path` set to outside $GITHUB_WORKSPACE does not work as the action does not allow it - this why the log show `ORT config ORT from https://github.com/oss-review-toolkit/ort-config.git`

```
    - name: Clone ORT config
      uses: actions/checkout@v2
      with:
        repository: alliander/ospo-ort-config
        path: ~/.ort/ort-config <= This is now allowed
        token: ${{secrets.XXX }}
```

Recommendation - update your script to the following:

```
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v2
      with:
        repository: alliander-opensource/weather-provider-api
        ref: main-2.0
        token: ${{secrets.XXX }}

    - name: OSPO License scanning
      uses: oss-review-toolkit/ort-ci-github-action@main
      with:
        ort-config-repository: 'https://oauth2:${{ secrets.XXX}}@github.com/alliander/ospo-ort-config.git'
        run: 'analyzer,labels,reporter,upload-results'
        sw-name: weather_provider_api
```
