### ISSUE TITLE
Missing exit code handling for scanner

### ISSUE THREAD

**Issue by DanielRuf** [oss-review-toolkit/ort-ci-github-action#21]
Somehow it does not continue after the scan has finished.

Do we have to change something regarding the error code handling (exited with statuscode 2)?

Used workflow config:

```yaml
name: Run ORT
on: [push]
jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      #- name: Use HTTPS instead of SSH for Git cloning
      #  run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@15297c37f35256c0e3a977c30771761ff51235d7
        with:
          run: >
            cache-dependencies,
            labels,
            analyzer,
            scanner,
            evaluator,
            advisor,
            reporter,
            upload-results

```
![grafik](https://user-images.githubusercontent.com/827205/233372217-158069d3-e727-477d-9acf-d7fa5d92afb8.png)
