### ISSUE TITLE
Passing Configuration files as arguments to Evaluator through the action file

### ISSUE THREAD

**Issue by saaskesaakura345** [oss-review-toolkit/ort-ci-github-action#24]
The analyzer arguments are succesfully taken by ORT through the action file.
I am trying to pass Configuration files as arguments to the Evaluator  ort-cli-evaluate-args: >
But lacking on how this can be achieved as I am receiving error

How should the configuration files be passed to Evaluator in the action file? 
~~~
jobs:
  ort:
    runs-on: ubuntu-latest
.
.
.
.
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          allow-dynamic-versions: 'true'
          ort-cli-analyze-args: >
            -l project=oss-project
            -l dist=external
            -l org=engineering-sdk-xyz-team-germany-berlin


       ort-cli-evaluate-args: >
         --resolutions-file ./resolutions.yml

~~~

![image](https://github.com/oss-review-toolkit/ort-ci-github-action/assets/128026849/8c823bf4-ae36-49eb-952d-5241e7b74400)

**Comment by georg-eckert-zeiss** [comment]
I found a workaround. When calling the action use:

```yml
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          allow-dynamic-versions: 'true'
          ort-home-path: 'work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.ort'
          

```
