### ISSUE TITLE
Action not using local ort config

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [oss-review-toolkit/ort-ci-github-action#35]
Hi everyone,

I have a repository using this action. Inside I have the following structure:

```
root-+-src/
     |
     +-.ort.yml
     |
     +-.ort/-+-config/-+-config.yml
                       |
                       +-curations.yml
```

None of those config files is used:

```
 ______________________________                                                
/        \_______   \__    ___/ The OSS Review Toolkit, version 22.7.0,        
|    |   | |       _/ |    |    built with JDK 11.0.23+9, running under Java 17
|    |   | |    |   \ |    |    Executing 'analyze' as 'ort' on Linux          
\________/ |____|___/ |____|    with 4 CPUs and a maximum of 5120 MiB of memory
                                                                               
Environment variables:                                                        
ORT_CONFIG_DIR = /home/ort/.ort/config                                        
ORT_DATA_DIR = /home/ort/.ort                                                 
HOME = /home/ort                                                              
JAVA_HOME = /opt/java/openjdk                                                 
ANDROID_HOME = /opt/android-sdk                                               
                                                                              
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml (does not exist)
Looking for analyzer-specific configuration in the following files and directories:
        /home/ort/work/<Repo-Name>/Repo-Name>/.ort.yml
        /home/ort/.ort/config/resolutions.yml
```

I already tried to set `ort-config-path` and `ort-home-path` - but neither seems to work.
So what is the correct way to use use those files?

Best regards,
Georg

**Comment by senthanal** [comment]
Hi
I also facing exactly same issue. Could someone help here?
Thanks in advance!

**Comment by maennchen** [comment]
Here's how I implemented this in Elixir:

https://github.com/elixir-lang/elixir/blob/main/.github/workflows/ort/action.yml#L42-L63

```yml
    - name: Fetch Default ORT Config
      id: fetch-default-ort-config
      uses: actions/checkout@v4
      with:
        repository: oss-review-toolkit/ort-config
        ref: "main"
        path: ".ort-config"

    - name: Setup ORT Config
      id: setup-ort-config
      shell: bash
      run: |
        mkdir -p "/$HOME/.ort/"

        # Move Fetched Default Config into Place
        mv .ort-config "/$HOME/.ort/config"
        
        # Append Global ORT Config
        cat .ort/config/config.yml >> "$HOME/.ort/config/config.yml"
        
        # Override Default Evaluator Rules
        cp .ort/config/evaluator.rules.kts "$HOME/.ort/config/evaluator.rules.kts"
```
