### ISSUE TITLE
ORT Scanner: invalid spec

### ISSUE THREAD

**Issue by elgohr** [oss-review-toolkit/ort-ci-github-action#37]
Adding scanner into the run parameter results in 
```
 Running ORT Scanner... 
docker: invalid spec: :/ssh.socket: empty section between colons.
See 'docker run --help'.
Error: Process completed with exit code 125.
```
Used configuration as
```yaml
name: Ort
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          run: 'cache-dependencies,analyzer,scanner,evaluator,advisor,reporter,upload-results'
      
```
